### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by emjrymer** [WomenWhoCode/WWCodeGreenville#1]

**Comment by klmansel** [comment]
- [ ] Add a brief description of the project to the repo
- [ ] Add a description to the README
- [ ] Add info on how to contribute to the project
- [ ] Add the Code of Conduct to the README

**Comment by heatherconard** [comment]
@klmansel Should i pull the code of conduct from the WWC website?

**Comment by klmansel** [comment]
@heatherconard You can copy the exact Code of Conduct from the [README.md](https://github.com/WomenWhoCode/WWCodeGreenville/blob/master/README.md)
