### ISSUE TITLE
Add an autolabeler

### ISSUE THREAD

**Issue by klmansel** [WomenWhoCode/WWCodeGreenville#118]
Add this GitHub Action autolabeler to the repo:
https://github.com/actions/labeler

- for the first pass, each directory should have a label with the directory name, downcased
- the readme and contributing docs should have a _documentation_ label

**Comment by weshaan** [comment]
Hey! I think i can do this, can you pls assign me, I'll update you in the afternoon. thank you :)

**Comment by klmansel** [comment]
> Hey! I think i can do this, can you pls assign me, I'll update you in the afternoon. thank you :)

Done! Comment here if you need any help tomorrow 😁

**Comment by weshaan** [comment]
Hey, I made some progress here. I've understood how the labeler action works and made a new workflow. this is ready for a pull request?

https://github.com/weshaan/WWCodeGreenville/tree/master/.github
![image](https://github.com/WomenWhoCode/WWCodeGreenville/assets/118920744/4bc6fae1-8bbe-4bf2-a94b-791e3a4fd829)

**Comment by JenBauer** [comment]
I haven't done this kind of work before, so let's do the pull request and see if it works.

Does this need to be a Github Action?  If so, the YAML file will live inside the workflows folder, if I understand this correctly.  I'm not versed in this, so apologies if I am mistaken here.  @klmansel may be the best person to tag as the reviewer on the PR, but I'm also interested in seeing how this is implemented.

Also, we will not need a Profiles label - I will be closing out that project shortly, as that was only for Hacktoberfest.

**Comment by weshaan** [comment]
Thank you for responding. there are two .yml files one in workflows to make the action work. another is to store lists of tags in .github folder. I'll remove the profiles tag and create a PR 👍
