### ISSUE TITLE
Cleanup of repo to follow code standards (TBD)

### ISSUE THREAD

**Issue by klmansel** [WomenWhoCode/WWCodeGreenville#126]
@JenBauer this is a placeholder, but I'd like to add some code standards for this repo including:

Use a Linter
Indentation and Spacing
Naming Conventions
Comments and Documentation
Consistent Bracing Style
File Structure
Limit Line Length
Imports and Dependencies
Error Handling

etc

**Comment by JenBauer** [comment]
I agree, but... all in one issue?!  You are an over achiever!  I'm also cool with this taking some time, or breaking this out to other folks in the chapter with more detail on what you are wanting as well.  Feel free to delegate. ;)

**Comment by klmansel** [comment]
> I agree, but... all in one issue?!  You are an over achiever!  I'm also cool with this taking some time, or breaking this out to other folks in the chapter with more detail on what you are wanting as well.  Feel free to delegate. ;)

Haha probably not all at once! It's a placeholder for the work for now!

**Comment by JenBauer** [comment]
I agree.  I bet there's some sort of standards doc somewhere we should reference.  Note to self to dig something up and link it here.

**Comment by JenBauer** [comment]
Adding a note here for the Events API project: we could use a JSON linter like https://github.com/zaach/jsonlint given that the majority of files will be JSON.

**Comment by JenBauer** [comment]
This repository will be inaccessible in the near future, so I am closing this issue.

Women Who Code has dissolved at a local and global level. Please visit https://linktr.ee/hackgvlwomen for more information and next steps on our Greenville community’s reorganizational efforts.
