### ISSUE TITLE
Add footer to homepage

### ISSUE THREAD

**Issue by klmansel** [WomenWhoCode/WWCodeGreenville#19]
**Add a footer to the homepage created in Issue #7 with the following:**

- [x] Link to the official WWC Homepage: https://www.womenwhocode.com
- [x] Link to our official WWC Homepage: https://www.womenwhocode.com/greenville
- [x] Link to sign up for our Slack channel: https://slackin-qsvgvhvawa.now.sh/

**Comment by klmansel** [comment]
@emjwivell Can you think of anything else to add to the footer for now? [Copyright 2020?](https://www.rapidtables.com/web/html/html-codes/html-code-copyright.html)

**Comment by emjwivell** [comment]
Copyright sounds great to me, @klmansel. How do we feel about also including social media links?

**Comment by klmansel** [comment]
Yes those too! If you can use Font Awesome icons for those, that’d be great
too Heather!

**Comment by heatherconard** [comment]
I can't figure out how to get the Font Awesome icons

**Comment by emjwivell** [comment]
I'm closing this issue.
