### ISSUE TITLE
Add images

### ISSUE THREAD

**Issue by emjrymer** [WomenWhoCode/WWCodeGreenville#22]
Load three test images into app/assets/images.

Dealers choice on the photos.

**Comment by emjwivell** [comment]
Hey @wendirodgers, how do you feel about picking up this issue?

**Comment by klmansel** [comment]
https://unsplash.com/s/photos/women-in-tech
https://unsplash.com/s/photos/laptop
 ^ Use these links @wendirodgers and download the photos to your laptop. Save them with normal names, not their original ones, and no spaces
