### ISSUE TITLE
Add a “table of contents” to our README.md

### ISSUE THREAD

**Issue by klmansel** [WomenWhoCode/WWCodeGreenville#58]
Using [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax), add a table of contents to the README.md. You can link whatever sections that are currently there, and create a general outline so we can add future sections

**Comment by Dianesaur** [comment]
Hi, I would like to contribute!

**Comment by Dianesaur** [comment]
Wait I am confused there seems to already be a table of contents and seems to link to the correct corresponding passages?

**Comment by JenBauer** [comment]
Hi @Dianesaur, you are correct.  I'm going to close this issue and make a few more issues that are more specific instead since this is essentially already complete.
