### ISSUE TITLE
Add links for WWCode Greenville to the README

### ISSUE THREAD

**Issue by klmansel** [WomenWhoCode/WWCodeGreenville#59]
Using [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) Add a list of (public only) links to where people can find our local chapter including Meetup, X(Twitter), Facebook, our WWCode network page, our open collective, etc

**Comment by prakartigoel24** [comment]
Please assign this to me.

**Comment by JenBauer** [comment]
I added a quick note on the PR to this to update the header and add two more links, and I think that should be it.

**Comment by JenBauer** [comment]
This is complete, closing.
