### ISSUE TITLE
Create a new "Current Chapter Members" section and subpage

### ISSUE THREAD

**Issue by JenBauer** [WomenWhoCode/WWCodeGreenville#61]
This issue is for creating the following deliverables for a new Current Members page:
- Create a new Markdown page noting current Women Who Code Greenville team members as noted in [this Notion page](https://wwcode.notion.site/WWCode-Greenville-Roster-df2c8f63d2df4f488fd094d37437f887?pvs=4).  Feel free to experiment with sections, tables, and other formatting options to relay this information in an interesting way.
- Link to this new page from the Table of Contents in [Readme.md](https://github.com/WomenWhoCode/WWCodeGreenville#readme)

**Comment by sergomen** [comment]
Hello! Pls assign it to me

**Comment by JenBauer** [comment]
Hey @sergomen, we have all different sorts of folks working in our repository outside of just the ladies in our chapter.  You are welcome to join in if you feel inspired.

**Comment by JenBauer** [comment]
I'll take this and link to the current Notion page from the Readme for the time being.  We can choose to be more creative than this in the future if needed.
