### ISSUE TITLE
Create a new page for Women Who Code Greenville Event Recordings

### ISSUE THREAD

**Issue by JenBauer** [WomenWhoCode/WWCodeGreenville#62]
This issue to create a new subpage related to Past Event Recordings, with links to those YouTube recordings:
- Create a new Markdown page for Past Event Recordings
- Link to related videos, found using the following search query within YouTube: [https://www.youtube.com/@WomenWhoCode/search?query=greenville](https://www.youtube.com/@WomenWhoCode/search?query=greenville)
- Copy in the event date and descriptive info from the event as you like.  Format this page in a way that will make sense for adding a large number of events in the future.
- Link to the new page from the [Readme](https://github.com/WomenWhoCode/WWCodeGreenville#readme) Table of Contents

**Comment by Nupoor10** [comment]
Hello, can I work on this?

**Comment by Nupoor10** [comment]
I won't be able to continue with this issue due to my impending exams. My apologies. I am unassigning myself from this issue.

**Comment by kodebae** [comment]
Just finished this issue and creating a PR for this now.

**Comment by JenBauer** [comment]
PR merged, closing.
