### ISSUE TITLE
Add a Chapter Highlights section and Recent Events sub section

### ISSUE THREAD

**Issue by JenBauer** [WomenWhoCode/WWCodeGreenville#64]
Let's highlight the last three events that our chapter hosted in a new section on the Readme page.
- Add a new section for Chapter Highlights on the Readme page.
-- If the Past Event Recordings issue is already completed by the point that this issue is started, let's move that link to here. 
- Add Recent Events as a subsection.  Use the Meetup page as a reference for which events were hosted specifically by Greenville (vs. Global events not hosted by our chapter)

**Comment by idrismusa4** [comment]
Hi!
Please Assign to me

**Comment by JenBauer** [comment]
Done, thank you @idrismusa4!

**Comment by JenBauer** [comment]
This repository will be inaccessible in the near future, so I am closing this issue.

Women Who Code has dissolved at a local and global level. Please visit https://linktr.ee/hackgvlwomen for more information and next steps on our Greenville community’s reorganizational efforts.
