### ISSUE TITLE
Create a basic home page

### ISSUE THREAD

**Issue by klmansel** [WomenWhoCode/WWCodeGreenville#7]
This page should have the Women Who Code logo and use the official Women Who Code colors

This issue will be updated with the assets necessary to complete the issue.

For now, all the page has to have is a logo that links to our official [WWCode website ](https://www.womenwhocode.com/greenville)

Wireframes are welcome to be added to this issue as suggestions for a future layout.

**Comment by emjwivell** [comment]
![Screen Shot 2019-10-25 at 10 12 48 AM](https://user-images.githubusercontent.com/16910302/67578227-03650400-f710-11e9-8808-d52fbb52df8e.png)

Maybe something like this to start out?
At the very least I think we should have:
- [ ] Logo
- [ ] Project tiles

[Here is Manila's site for reference.](https://wwcodemanila.github.io/)

**Comment by klmansel** [comment]
@heatherconard I am going to add some assets (images, colors) you can use to make a basic homepage using HTML and CSS. For the sake of time, I'm not going to have you fork the repo - we can do that next week at WWCode. I'll show you how to add your file directly to Github.

**Comment by klmansel** [comment]
![WWCode_Greenville_Binary_NEW TEAL](https://user-images.githubusercontent.com/18410214/67902644-09a81580-fb40-11e9-99ce-da0b23d2f1d1.jpg)

**Comment by klmansel** [comment]
<img width="841" alt="Screen Shot 2019-10-30 at 6 07 18 PM" src="https://user-images.githubusercontent.com/18410214/67902726-3bb97780-fb40-11e9-884d-29c380e36073.png">

**Comment by klmansel** [comment]
@heatherconard *HUGE HINT:* Don't overthink this at all....the logo and 8 tiles is fine for now!

**Comment by heatherconard** [comment]
@klmansel @emjwivell where should it get the images for the tiles? I don't want to pull from somewhere that could be removed later on and cause issues.

**Comment by klmansel** [comment]
For the tiles, I think the logos for: Python, Ruby, Javascript, Data (you
can use the SQL or database symbol), PHP, and WordPress should be fine for
now - those should be available in Google Images - I know I found ones from
the same set for a project I did earlier this year!

**Comment by klmansel** [comment]
Also @heatherconard we will definitely change the images very soon and use a standard SVG set or something, so don't worry too much about what the images look like.
