### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by git-create-devben** [WomenWhoCode/WWCodeGreenville#91]
Suggesting of adding example of how to contribute to the repo because of people who are new to open source and this will be their first contribution. 

Example of how it will look:

Fork the repository. You can do this by clicking the "Fork" button on the repository's page on GitHub.
Clone the forked repository to your local machine. Open a terminal and navigate to the directory where you want to clone the repository. Then, run the following command:

`git clone https://github.com/<your_username>/<repo_name>.git`

Replace <your_username> with your GitHub username and <repo_name> with the name of the repository that you forked.

Create a new branch. To do this, run the following command:

`git checkout -b <branch_name>`

Replace <branch_name> with the name of the branch that you want to create.

Make your changes. Open the file(s) that you want to edit and make your changes.

Commit your changes. To do this, run the following command:

`git commit -m "<commit_message>"`

Replace <commit_message> with a short message that describes your changes.

Push your changes to your forked repository. To do this, run the following command:

`git push origin <branch_name>`

Replace <branch_name> with the name of the branch that you pushed your changes to.

You will see compare pull request on your Github click on it 

OR

Create a pull request. Go to the repository's page on GitHub and click the "Pull requests" tab. Then, click the "New pull request" button.
Select the branch that you pushed your changes to and write a pull request description. Then, click the "Create pull request" button.

Respond to feedback. The maintainers of the repository may review your changes and suggest improvements. Respond to their feedback and make any necessary changes.

Merge your pull request. Once the maintainers are happy with your changes, they will merge your pull request into the main branch of the repository.

I'll be happy to contribute assign me.

**Comment by klmansel** [comment]
@git-create-devben Thanks! This would be great. Can you add these steps along with links to the GitHub documentation to a file called `gettingstarted.md`  and link it in the README?

**Comment by JenBauer** [comment]
Funny enough, we did have a contribution doc, but it was wiped out the other day.  I'm not sure if some of it could've been useful or at least could have stayed, in retrospect.

**Comment by klmansel** [comment]
Ah, I probably deleted it on my fresh start branch 🤦🏽‍♀️

**Comment by lucashchang** [comment]
Can i be assigned?

**Comment by ShilpiBG12** [comment]
Can I be assigned updation of gettingstarted.md file? Also, in case you can assign, please tell me what contents need to be added to this file.
Thanks

**Comment by klmansel** [comment]
this has been completed #96 - thanks again @git-create-devben!
